// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkFWgcsVzpbLClY_UWaSKYHPAJ12UUiaI',
    appId: '1:49697631303:web:f2b1948f008e47f632d562',
    messagingSenderId: '49697631303',
    projectId: 'chatapp-397f5',
    authDomain: 'chatapp-397f5.firebaseapp.com',
    storageBucket: 'chatapp-397f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDad0EM_2JFia9EfFwyvH-JxRNhc8PnmGE',
    appId: '1:49697631303:android:2203179b0861f54a32d562',
    messagingSenderId: '49697631303',
    projectId: 'chatapp-397f5',
    storageBucket: 'chatapp-397f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMkiz7X_Fcn-nJSsMnagGEcDwWA9YexEo',
    appId: '1:49697631303:ios:0c7940e4dec7c90d32d562',
    messagingSenderId: '49697631303',
    projectId: 'chatapp-397f5',
    storageBucket: 'chatapp-397f5.appspot.com',
    iosClientId: '49697631303-j30ja8ltvhtc5rrbeainkb46etsugvar.apps.googleusercontent.com',
    iosBundleId: 'com.example.convertLangApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMkiz7X_Fcn-nJSsMnagGEcDwWA9YexEo',
    appId: '1:49697631303:ios:0547812ac56eb3b432d562',
    messagingSenderId: '49697631303',
    projectId: 'chatapp-397f5',
    storageBucket: 'chatapp-397f5.appspot.com',
    iosClientId: '49697631303-202vh4ll4btnir259avcu828srbqcfl9.apps.googleusercontent.com',
    iosBundleId: 'com.example.convertLangApp.RunnerTests',
  );
}
